language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonar-key-for-koady
    token:
      secure: "rphc5gSzdsO8StQyZBaSSLxoHawFImHQi+RzUjgjpC8fz0xSayBv0w62Y5Of3j19Byn01WNsCw3+tNdPKP8DU73MW3NmeuzVTNz+00RasXu/q1YVQTgUdGW+PGWrz0wcnfyiOeQSQBa+GM/A6X8Xis4W1N1j54cVOSm1dSjz1tQl0RIHZYB5CG5zxSjJCH648XZ50OgqgdK/YIByuBcAY6WH0CSoKK8qCW2mN2lFWs2a30FIgW4S405rt4inx0oeAhtjKmjPRGUm9hPeV1Q+HzTzgdpPT61Rmbss8cCQAYePg6FzKvZRZpa7rkaYkJVqkvhM+5hvy/SicCdSIbvkm3DZC/hq+04NAS7gueg+EiCqZEuuG7vXRjFuazjUUsR8n90Eyb8AXQuFN0O9kvqLVFM19uDNclkL/ZKev1Lnx/rnGSghaRRikmh/8/3UaQb7OdnJluEBiMc6YFpMapoP2/sNYHrvCykU1bofSu+QxTvlMbnofFztNlsjn0tUnMZkJ5a7M5RmzNQlcAaPDAzTC89Nhn+3+yBTlTct+pqnl33VZMXMyte22csAKGWSM83CRWSVB68bsTYDZ1H232QdYAQMwxKvj1fk/3ctqm2HYQOWOchhSJ98fWEkvwngLzW/20w4KYXx4vc1PtYi2wqUvwydTF7rSEtaUcC8Y/FAuUY="
script:
- sonar-scanner
env:
  global:
  - secure: rphc5gSzdsO8StQyZBaSSLxoHawFImHQi+RzUjgjpC8fz0xSayBv0w62Y5Of3j19Byn01WNsCw3+tNdPKP8DU73MW3NmeuzVTNz+00RasXu/q1YVQTgUdGW+PGWrz0wcnfyiOeQSQBa+GM/A6X8Xis4W1N1j54cVOSm1dSjz1tQl0RIHZYB5CG5zxSjJCH648XZ50OgqgdK/YIByuBcAY6WH0CSoKK8qCW2mN2lFWs2a30FIgW4S405rt4inx0oeAhtjKmjPRGUm9hPeV1Q+HzTzgdpPT61Rmbss8cCQAYePg6FzKvZRZpa7rkaYkJVqkvhM+5hvy/SicCdSIbvkm3DZC/hq+04NAS7gueg+EiCqZEuuG7vXRjFuazjUUsR8n90Eyb8AXQuFN0O9kvqLVFM19uDNclkL/ZKev1Lnx/rnGSghaRRikmh/8/3UaQb7OdnJluEBiMc6YFpMapoP2/sNYHrvCykU1bofSu+QxTvlMbnofFztNlsjn0tUnMZkJ5a7M5RmzNQlcAaPDAzTC89Nhn+3+yBTlTct+pqnl33VZMXMyte22csAKGWSM83CRWSVB68bsTYDZ1H232QdYAQMwxKvj1fk/3ctqm2HYQOWOchhSJ98fWEkvwngLzW/20w4KYXx4vc1PtYi2wqUvwydTF7rSEtaUcC8Y/FAuUY=
