language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonarcloud
    token:
      secure: "*********"
script:
- sonar-scanner -X
env:
  global:
  - secure: ho4u62GSjLapv37E6eXNeXGDhYH1X1pL2v/eMAT+mkxxmjJEPp6I/QmHSiKfZCuSrrrenvPOgpqabtxchB9nVG6ouZ/OYjB46iGzMje3F7uuGjj6lJHdhXV9ZVnTNnUk0dZS0py3Xsm8slYIgsr/3IS1oQRyPIdlw0PfUK48TstMqlcGqzUJY1jyQfeytV1UPYBw77IZc2acybFoO8aYv5Uwf83seeSscMCE3AoryrWijtEtg28zJnsjGB7LqZl3p4pUv9eUoV8E3g24KbV26ulAHGslWi2VvHOhCrDe+tRHQPVh74L2E2iatYm8dLwb0TihH221zvzGjGjYyJZGXEE5Pgj2LQedEm2rKYiRNvXNjtIWd+q78ApXuhfs+ZAqKhRh6I1Jh5+Qr5HCUYLXLmcctc7EZDdHtd0nyVbp7TAv5SFLVslMnItOX3c4/WBqoaO5xbkN49lY8tW2qkHmG/s9BLaxCj3PJwwFd2ZNy+xk2cXxZu+TcEcicrDM5kMUe/HO3bCyEbN+BFV7PStJ3l3xIeALVbhEcyM03EaFIQz6Y15i+sJ7l0XbwRed/SsWcYdaTqfHeRs2FLJVPmtSzJMsTq9sxaMkkCrA45d4sxRVHcQXp+mwLiTUTrOdNCyxj7Fk8h992pcgbZhMgwgq9bEXbqR3ECgrerxoz7C7riM=
  - secure: MFVgqJ52Cj4HqjUU/Kg8BS+NTZ3c9U+JWqPhhHwUJSWYxqYsY/Z2XheymV0NZuvcUvQVwEeihww0KFne2CPlkBLr/2rrZY5Cv8Tr9UQZuM/7vBXjYfNxk5xUqlAIHrmVznC5u/1K6o5doAcf2uCffFW4v0S6S+7XOH4Qyirw8xuDE5VDeXkmQ3jK9bWUgl3RhdckubiOnAjVf6OZ/pPiVonXFcbPci2hLFGy9qmWdv566UAlcqVbae5BMgiRidJdZYVyFypnQK0TE4yy9VIj7ax8EsmpJIwT0Su7BsE5QNz7rLpcTwRiIf2wUeM30uYM/fdUklBmBwoE9tIB57hZS+IGxY0wTgps3YU0149cscMkr63op01ZbLlxYpgCMUWwZCck3h3CD6tQLd0sZ/Ce5pDwHUcqezE3SnTjYDJ5wN3oc3NfOzM0C6UlqMC4cp1HXMPq1Bj+/uXG5M48sCXeCohVFQg7Jb1QXcBKkNQpPe5wf6B0I6egfQIGkE5+7FDT9uy9vDfyYtHXSAg+Ra6OKkwoovxMGntY2sqV/W7/12Q0DKIo6cAg7F4KmlKQwt+tFtS/qGB52oEF8ohuCdCExgTK68Hhm3lOPa95qw3uBga1vrUYnBnMPPB+kh0o+PnZ7Tflh9Cvibt7Y2au4Q+GY+S8Dto9MyfbJkpfoyFWilU=
