language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonarcloud
    token:
        secure: "itdshH2wFRYEZlP0DIF7vVFzkjwkagrWY2espqgHVD8ZnHfUn9uSE9ulUzehKAGcX0xBG2+Sp5w4e73XEoNTL1r1PJfvjB1haDJSoW6ZEyik4DrCblhaJo9ERmoGvRaSww1P5Qm9UN4fUicqJQQtLWkJkmaNdxMc8J15bVK1fALPVfT0V/qwwtxDMD5rlheAmgZ1mXyhTMLETJviKBY7oO3lTyGpHCi2YBSQADNQlLY53UmHGKMBRNQFWdXdFmfavITPtk/pQoGWVPc1j3CKN2n7JT8k/m+pQZ3Q98zYvT2OYm493mn77wFk1J5FRYr3yeOyzyv09oT9BQFuIUcOvYaz8cDh0zD4ZQaSZGTn307/jLX/SKmxd4l0cBU/W7bC6wFu3bxkMUmn5lFLfP/Av1R+n6co8TR2IsnH2/AmvRSFwjJ001L8eX7QRKDEl2CVTbtbh9GFAjkZi3Q4EsIKrG+xypD2PvKxhC1PePOGKAxbWfZDvljKQsFfOgMgFNdaFKCJveErsx4yXWC0PbY/+0KOeFThPmcuAKoZF2oIRWkYakaibvoSaQDP1BeCNhIPOcQmjktofBQabtZvmq/ze70ef4Lj3xyTUTorGuSlV7hWN9gUJhXlScd27FNDEJ1/PRFEZlsVNiFATXzq94kWTWA2m6HCV74s6rbP/GeRm4Q="
script:
- sonar-scanner -X
