language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonarcloud
    token: ${SONAR_TOKEN}
script:
- sonar-scanner -X
env:
  SONAR_TOKEN:
    secure: phbj6rlTTvEbgXQO1rk9NzZ5kqESWmnzCDiNWqvndNWYrEuW6Pt3bMNg4U+i6HA682Lx6VKUEEEs1ejdNQ/b/OwrVTv6rx2wJN0uc8NzoF791P7ET1QYp5W4A8IVKqU8HxBnJevnMs02eio92EMVSOTHqFX3Egq6cVF8bdzjC1C/8Qv/7Ts941Y9YBtjsgMXyqgyL+xJ595EgvJz7+PsDpNgAPXz/yPvT9H7ul6JWOX7336NGRRSyHK4TO4acqYSXNdCZ9ir2h3MD4E2WGox7X/h00M79nzKj4KZrQzcCIqKn+0s5P9lXlrERqO/ZDW+uq+hxF858Jdsgy9hn6TS9hU1PRiAXdhlkJP/y0uIQ+DkliPB1QO+jjFgq8uHdrHmvYTi+gpZNuEvgIsv/vIubUFjj70aiuEj7xCqR9nNysvjwv8Ja1+6eO/rr840etUjvt5PoblU/dvmONW5/tHNd5Ki9I34cyyz+U3TUb3yko/VOqV9K0Vzj5VDyQLGDjV9PBf57cvdzpiEA3Nlc8uVaprKbZmbC98C6t227BmBB19zNmLKJgejPScrTpoLERsJkIhCj0eA5/dlcZfEzbKETZbvDYOm1EEmNYatEIt4GtPEhGvn/Yjhf18GLV9AWhFuYUAyskUTUYVSOlxKHnZyiuVwudNNnaPShR9eKCpditM= #1866c4c2d7c963bd98fd6cc7f41466de26e962b5 #1866c4c2d7c963bd98fd6cc7f41466de26e962b5
