language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonarcloud
    token:
        secure: "zQvRldr1+LAUHDn7tvUYAP3OEu93hKHrW+ATXKsqUOr0Q6587er3JMoGfWn2R2BOtMLK7/8Vf2kwfTGlzGGLGqsTYYyjBOzkBHUvjbIZepydIkgb9yBLw1D4xDrIWpPHA9SzZR5Qwwq8MZXJpWLDeTuXV4wfxpSqbsuUQq42eh1SKDxtt8aidjIQHDXznxEeY4SIE3sG/ntKZg/9vjpuybX2U48NCvZIw7C9zFrp38vvzQHaLmOL5Ct6cVN4K2Gj3Qk+IySysLq52o6bs9VkL6MhULLer5TrxQtYbi3Bx3e54I356L/VAT5bBNfnizeR61UFRHf4IFETONr7mZIrxTgxK+TS4ln4zBZA40OQAEu0V2sZx6xBZdGWferQYIoPyHYqGF69QgYA6d8w5OiRtLESFbSWaNWptVF/frnJ6G8huuPUJv85YCx9dDvuQ1VmY6f231Iyhjqyik1BuPSFy0pdrBEwK5sRImV9AWNfMVeYLkSmsKv6hJSLCJKM5Ho9fxovRGj9bZWLLdFZ8CBQ37Ag8YYo8IEMbhF8YlxNtZjrpXo5kzmIRjva/NC6T2nPej4B/2dVRFMIcET5dQT02SlEUNQVqmfLAeowE3hDIPdS3chyL0j8glUJcq2W+BzQlR9zyM5a2cmbkIltayUT0x/OssJxQMc/WuKWz0bHVjg="
script:
- sonar-scanner -X
