language: node_js
node_js:
- lts/*
- node
dist: trusty
addons:
  sonarcloud:
    organization: sonarcloud
    token:
      secure: "*********"
script:
- sonar-scanner -X
env:
  global:
    secure: ho4u62GSjLapv37E6eXNeXGDhYH1X1pL2v/eMAT+mkxxmjJEPp6I/QmHSiKfZCuSrrrenvPOgpqabtxchB9nVG6ouZ/OYjB46iGzMje3F7uuGjj6lJHdhXV9ZVnTNnUk0dZS0py3Xsm8slYIgsr/3IS1oQRyPIdlw0PfUK48TstMqlcGqzUJY1jyQfeytV1UPYBw77IZc2acybFoO8aYv5Uwf83seeSscMCE3AoryrWijtEtg28zJnsjGB7LqZl3p4pUv9eUoV8E3g24KbV26ulAHGslWi2VvHOhCrDe+tRHQPVh74L2E2iatYm8dLwb0TihH221zvzGjGjYyJZGXEE5Pgj2LQedEm2rKYiRNvXNjtIWd+q78ApXuhfs+ZAqKhRh6I1Jh5+Qr5HCUYLXLmcctc7EZDdHtd0nyVbp7TAv5SFLVslMnItOX3c4/WBqoaO5xbkN49lY8tW2qkHmG/s9BLaxCj3PJwwFd2ZNy+xk2cXxZu+TcEcicrDM5kMUe/HO3bCyEbN+BFV7PStJ3l3xIeALVbhEcyM03EaFIQz6Y15i+sJ7l0XbwRed/SsWcYdaTqfHeRs2FLJVPmtSzJMsTq9sxaMkkCrA45d4sxRVHcQXp+mwLiTUTrOdNCyxj7Fk8h992pcgbZhMgwgq9bEXbqR3ECgrerxoz7C7riM=
